services:
  api:
    build:
      context: ./sdv-api
      dockerfile: Dockerfile
      target: dev
    ports:
      - "80:80"
    volumes:
      - ./sdv-api:/app
    command: ["cargo", "run", "--release"]

  web:
    build:
      context: ./sdv-web
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./sdv-web:/usr/src/app
    environment:
      - API_URL=http://api
    command: ["npm", "run", "dev"]