name: CI/CD Pipeline

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-dev:
    name: Build and Push Dev Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Dev Image
        run: docker build -f sdv-api/Dockerfile --target dev -t ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest ./sdv-api

      - name: Push API Dev Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest

      - name: Build Web Dev Image
        run: docker build -f sdv-web/Dockerfile --target dev -t ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest ./sdv-web

      - name: Push Web Dev Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest

  build-and-push-prod:
    name: Build and Push Prod Image
    runs-on: ubuntu-latest
    needs: build-and-push-dev  # Assure que le job de dev s'exécute en premier

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Prod Image
        run: docker build -f sdv-api/Dockerfile --target prod -t ${{ secrets.DOCKER_USERNAME }}/sdv-api-prod:latest ./sdv-api

      - name: Push API Prod Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sdv-api-prod:latest

      - name: Build Web Prod Image
        run: docker build -f sdv-web/Dockerfile --target prod -t ${{ secrets.DOCKER_USERNAME }}/sdv-web-prod:latest ./sdv-web

      - name: Push Web Prod Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sdv-web-prod:latest