name: CI/CD Pipeline

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub (First Repo)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Dev Image
        run: docker build -f sdv-api/Dockerfile -t myapp-api-dev:latest ./sdv-api

      - name: Build Web Dev Image
        run: docker build -f sdv-web/Dockerfile -t myapp-web-dev:latest ./sdv-web

      - name: Tag and Push API Dev Image to First Repo
        run: |
          docker tag myapp-api-dev:latest ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest

      - name: Tag and Push Web Dev Image to First Repo
        run: |
          docker tag myapp-web-dev:latest ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest

      - name: Log in to Docker Hub (Second Repo)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push API Dev Image to Second Repo
        run: |
          docker tag myapp-api-dev:latest ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest

      - name: Tag and Push Web Dev Image to Second Repo
        run: |
          docker tag myapp-web-dev:latest ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest